"""Initial migration.

Revision ID: cd6a5a268126
Revises: db29fb1de3a9
Create Date: 2024-01-26 10:19:07.156770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6a5a268126'
down_revision = 'db29fb1de3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('materials', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('instruction_title', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('instruction_description', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=1000), nullable=True))
        batch_op.drop_column('post_title')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_title', sa.VARCHAR(length=1000), nullable=True))
        batch_op.drop_column('reference')
        batch_op.drop_column('instruction_description')
        batch_op.drop_column('instruction_title')
        batch_op.drop_column('materials')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
