"""empty message

Revision ID: db29fb1de3a9
Revises: 
Create Date: 2024-01-26 09:47:30.180514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db29fb1de3a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('materials', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('instruction_title', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('instruction_description', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=1000), nullable=True))
        batch_op.drop_column('post_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_title', sa.VARCHAR(length=1000), nullable=True))
        batch_op.drop_column('reference')
        batch_op.drop_column('instruction_description')
        batch_op.drop_column('instruction_title')
        batch_op.drop_column('materials')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
